disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - file_header
  - xct_specific_matcher
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - JLRSharedPackage/Testing/Sources/Testing/Testing.docc
  - DerivedData
  - .build
  - dangerfile.swift
file_header:
  required_pattern: |
    \/\/
    \/\/  Created by .*? on .*?
    \/\/  Copyright © Jaguar Land Rover Ltd \d{4} All rights reserved\.
    \/\/  This software is confidential and proprietary information\.
    \/\/.*?
line_length:
  warning: 150
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 800
large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 4
function_parameter_count:
  warning: 6
identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - up
    - to
    - ok
    - dk
    - eu
    - at
    - qa
    - qc
    - us
    - uk
    - wh
    - !str no
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone
    - S
reporter: "xcode"
